version: "3.8"
services:
  app:
    build: .
    container_name: webrtc-app
    environment:
      - PORT=4000
      - ORIGIN=https://${CADDY_DOMAIN}
      - DATABASE_PATH=./data/app.sqlite
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - appdata:/app/server/data
    expose:
      - "4000"
    restart: unless-stopped
    depends_on:
      - turn
  caddy:
    image: caddy:2
    container_name: webrtc-caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - CADDY_EMAIL=${CADDY_EMAIL}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddydata:/data
      - caddyconfig:/config
    depends_on:
      - app
    restart: unless-stopped
  turn:
    image: coturn/coturn:4.5
    container_name: webrtc-turn
    network_mode: host
    environment:
      - TURN_REALM=${TURN_REALM}
      - TURN_USER=${TURN_USER}
      - TURN_PASS=${TURN_PASS}
    volumes:
      - ./turn/turnserver.conf:/etc/turnserver.conf:ro
    command: ["-c", "/etc/turnserver.conf"]
    restart: unless-stopped

volumes:
  appdata:
  caddydata:
  caddyconfig:
